# Generated by Django 6.1 on 2026-08-18 13:05

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(editable=False, max_length=12, unique=True, verbose_name='Takip Kodu')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık / Konu')),
                ('description', models.TextField(verbose_name='Açıklama / Detay')),
                ('district', models.CharField(max_length=100, verbose_name='İlçe')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mahalle')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Konum')),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('IN_PROGRESS', 'İnceleniyor'), ('RESOLVED', 'Çözüldü'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=20, verbose_name='Durum')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ticket_images/', verbose_name='Fotoğraf')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Talep / Şikayet',
                'verbose_name_plural': 'Talepler / Şikayetler',
                'ordering': ['-created_at'],
            },
        ),
    ]
