# Generated by Django 6.1 on 2026-08-19 07:48

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Birim Adı')),
                ('address', models.TextField(verbose_name='Adres')),
                ('address_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adres Tarifi')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Mahalle')),
                ('district', models.CharField(max_length=100, verbose_name='İlçe')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Konum')),
            ],
            options={
                'verbose_name': 'Çözüm Noktası',
                'verbose_name_plural': 'Çözüm Noktaları',
                'ordering': ['district', 'name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='sector',
            field=models.CharField(choices=[('ULASIM', 'Ulaşım'), ('CEVRE_KENT_TOPLUM', 'Çevre, Kent ve Toplum Düzeni'), ('ISKI', 'İSKİ'), ('IGDAS', 'İGDAŞ'), ('SAGLIK_SOSYAL', 'Sağlık ve Sosyal Destek'), ('IMAR_ALTYAPI', 'İmar ve Altyapı Faaliyetleri'), ('DIGER', 'Diğer')], default='DIGER', help_text="Dashboard'da İBB açık veri istatistikleriyle karşılaştırma için kullanılır.", max_length=30, verbose_name='İBB Sektörü'),
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_unit', models.CharField(choices=[('FEN_ISLERI', 'Fen İşleri'), ('TEMIZLIK', 'Temizlik İşleri'), ('PARK_BAHCE', 'Park ve Bahçeler'), ('SU_KANAL', 'Su ve Kanalizasyon'), ('ZABITA', 'Zabıta'), ('DIGER', 'Diğer')], max_length=30, verbose_name='Atanan Birim')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Saha Notu / Açıklama')),
                ('resolution_image', models.ImageField(blank=True, null=True, upload_to='resolution_images/', verbose_name='Çözüm Sonrası Fotoğraf')),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Önceki Durum')),
                ('new_status', models.CharField(max_length=20, verbose_name='Yeni Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_resolutions', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan Personel')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='tickets.ticket', verbose_name='İlgili Talep')),
            ],
            options={
                'verbose_name': 'Çözüm / İş Kaydı',
                'verbose_name_plural': 'Çözüm / İş Kayıtları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectoralStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Yıl')),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ay')),
                ('period_type', models.CharField(choices=[('YEARLY', 'Yıllık'), ('MONTHLY', 'Aylık')], max_length=10, verbose_name='Periyot Tipi')),
                ('sector', models.CharField(choices=[('ULASIM', 'Ulaşım'), ('CEVRE_KENT_TOPLUM', 'Çevre, Kent ve Toplum Düzeni'), ('ISKI', 'İSKİ'), ('IGDAS', 'İGDAŞ'), ('SAGLIK_SOSYAL', 'Sağlık ve Sosyal Destek'), ('IMAR_ALTYAPI', 'İmar ve Altyapı Faaliyetleri'), ('DIGER', 'Diğer')], max_length=30, verbose_name='Sektör')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Yüzde (%)')),
            ],
            options={
                'verbose_name': 'Sektörel İstatistik',
                'verbose_name_plural': 'Sektörel İstatistikler',
                'ordering': ['year', 'month'],
                'unique_together': {('year', 'month', 'period_type', 'sector')},
            },
        ),
    ]
