# Generated by Django 6.1 on 2026-08-19 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_solutioncenter_category_sector_resolution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_unit',
            field=models.CharField(choices=[('FEN_ISLERI', 'Fen İşleri'), ('TEMIZLIK', 'Temizlik İşleri'), ('PARK_BAHCE', 'Park ve Bahçeler'), ('SU_KANAL', 'Su ve Kanalizasyon'), ('ZABITA', 'Zabıta'), ('DIGER', 'Diğer')], default='DIGER', help_text='Bu kategoride açılan talepler otomatik olarak bu birime düşer.', max_length=30, verbose_name='Sorumlu Birim'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='current_unit',
            field=models.CharField(blank=True, choices=[('FEN_ISLERI', 'Fen İşleri'), ('TEMIZLIK', 'Temizlik İşleri'), ('PARK_BAHCE', 'Park ve Bahçeler'), ('SU_KANAL', 'Su ve Kanalizasyon'), ('ZABITA', 'Zabıta'), ('DIGER', 'Diğer')], max_length=30, null=True, verbose_name='Atanan Birim'),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('FEN_ISLERI', 'Fen İşleri'), ('TEMIZLIK', 'Temizlik İşleri'), ('PARK_BAHCE', 'Park ve Bahçeler'), ('SU_KANAL', 'Su ve Kanalizasyon'), ('ZABITA', 'Zabıta'), ('DIGER', 'Diğer')], max_length=30, verbose_name='Çalıştığı Birim')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Personel Profili',
                'verbose_name_plural': 'Personel Profilleri',
            },
        ),
    ]
