# Generated by Django 5.2.17 on 2026-08-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_category_default_unit_ticket_current_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolution',
            name='new_status',
            field=models.CharField(choices=[('PENDING', 'Beklemede'), ('IN_PROGRESS', 'İnceleniyor'), ('RESOLVED', 'Çözüldü'), ('REJECTED', 'Reddedildi')], max_length=20, verbose_name='Yeni Durum'),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Beklemede'), ('IN_PROGRESS', 'İnceleniyor'), ('RESOLVED', 'Çözüldü'), ('REJECTED', 'Reddedildi')], max_length=20, null=True, verbose_name='Önceki Durum'),
        ),
    ]
