# Generated by Django 5.2.17 on 2026-08-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_resolution_new_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta (bildirim için)'),
        ),
    ]
