# Generated by Django 5.2.17 on 2026-08-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='support_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Destek Sayısı'),
        ),
    ]
