# Generated by Django 5.2.17 on 2026-08-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_support_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('otp_code', models.CharField(max_length=6, verbose_name='Doğrulama Kodu')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Doğrulandı mı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Telefon Doğrulama',
                'verbose_name_plural': 'Telefon Doğrulamaları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası (Doğrulanmış)'),
        ),
    ]
