# Generated by Django 5.2.17 on 2026-08-27 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_phoneverification_ticket_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Soru / Etiket')),
                ('field_type', models.CharField(choices=[('text', 'Kısa Metin'), ('textarea', 'Uzun Metin'), ('number', 'Sayı'), ('date', 'Tarih'), ('choice', 'Seçenekli (Tek Seçim)'), ('boolean', 'Evet / Hayır')], default='text', max_length=20, verbose_name='Alan Tipi')),
                ('choices_text', models.CharField(blank=True, help_text="Sadece 'Seçenekli' tipi için geçerlidir. Örn: Evet, Hayır, Bilmiyorum", max_length=500, null=True, verbose_name='Seçenekler (virgülle ayırın)')),
                ('is_required', models.BooleanField(default=True, verbose_name='Zorunlu mu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_fields', to='tickets.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Dinamik Form Alanı',
                'verbose_name_plural': 'Dinamik Form Alanları',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DynamicFieldResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, verbose_name='Cevap')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='tickets.dynamicfield', verbose_name='Alan')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_responses', to='tickets.ticket', verbose_name='Talep')),
            ],
            options={
                'verbose_name': 'Dinamik Alan Cevabı',
                'verbose_name_plural': 'Dinamik Alan Cevapları',
            },
        ),
        migrations.CreateModel(
            name='FormFieldAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_label', models.CharField(max_length=200, verbose_name='Alan/Soru')),
                ('action', models.CharField(choices=[('CREATE', 'Oluşturuldu'), ('UPDATE', 'Güncellendi'), ('DELETE', 'Silindi'), ('REORDER', 'Sıralandı')], max_length=10, verbose_name='İşlem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tickets.category', verbose_name='Kategori')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
            ],
            options={
                'verbose_name': 'Form Değişiklik Kaydı',
                'verbose_name_plural': 'Form Değişiklik Kayıtları',
                'ordering': ['-created_at'],
            },
        ),
    ]
