# Generated by Django 5.2.17 on 2026-09-01 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_dynamicfield_dynamicfieldresponse_formfieldauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Adresi')),
                ('session_key', models.CharField(max_length=40, verbose_name='Oturum Anahtarı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporters', to='tickets.ticket', verbose_name='Talep')),
            ],
            options={
                'verbose_name': 'Talep Desteği',
                'verbose_name_plural': 'Talep Destekleri',
                'unique_together': {('ticket', 'ip_address', 'session_key')},
            },
        ),
    ]
