# Generated by Django 5.2.17 on 2026-09-01 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_ticket_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='internal_note',
            field=models.TextField(blank=True, null=True, verbose_name='İç Not (Sadece Personel Görür)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='citizen_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Vatandaş Geri Bildirimi'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='citizen_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Vatandaş Puanı (1-5)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rating_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Puanlama Tarihi'),
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_type', models.CharField(choices=[('CITIZEN', 'Vatandaş'), ('STAFF', 'Personel')], max_length=10, verbose_name='Yazan')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('staff_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Personel (varsa)')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket', verbose_name='Talep')),
            ],
            options={
                'verbose_name': 'Talep Yorumu',
                'verbose_name_plural': 'Talep Yorumları',
                'ordering': ['created_at'],
            },
        ),
    ]
