# Generated by Django 5.2.17 on 2026-09-02 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_resolution_internal_note_ticket_citizen_feedback_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='URL Kısaltması')),
                ('summary', models.CharField(max_length=300, verbose_name='Kısa Özet')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='article_images/', verbose_name='Kapak Görseli')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayında mı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'verbose_name': 'Bilgilendirme Makalesi',
                'verbose_name_plural': 'Bilgilendirme Makaleleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
