# Generated by Django 5.2.17 on 2026-09-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='is_content_editor',
            field=models.BooleanField(default=False, verbose_name='Makale Yazma Yetkisi'),
        ),
    ]
