# Generated by Django 5.2.17 on 2026-09-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_staffprofile_is_content_editor'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('FEN_ISLERI', 'Fen İşleri'), ('TEMIZLIK', 'Temizlik İşleri'), ('PARK_BAHCE', 'Park ve Bahçeler'), ('SU_KANAL', 'Su ve Kanalizasyon'), ('ZABITA', 'Zabıta'), ('DIGER', 'Diğer')], max_length=30, unique=True, verbose_name='Birim')),
                ('target_hours', models.PositiveIntegerField(verbose_name='Hedef Çözüm Süresi (Saat)')),
            ],
            options={
                'verbose_name': 'Birim Hedef Süresi (SLA)',
                'verbose_name_plural': 'Birim Hedef Süreleri (SLA)',
            },
        ),
    ]
